### ISSUE TITLE
Won't install on VS2010 .NET 4.0

### ISSUE THREAD

**Issue by johncblacker** [LutsenkoKirill/AlphaVantage.Net#10]
I'm trying to install this via package manager and it won't install.  Here's what I get:
------------------------ pm output --------------------------------
Install failed. Rolling back...
Install-Package : Could not install package 'AlphaVantage.Net.Stocks 1.0.2'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more 
information, contact the package author.
At line:1 char:1
+ Install-Package AlphaVantage.Net.Stocks -Version 1.0.2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 ---------------------- end of pm output ------------------------------------

**Comment by LutsenkoKirill** [comment]
@johncblacker this library compiled to work with .Net Standard 2.0+ which is not supported in Net Framework 4.0. 
Unfortunately, I have no time to support legacy framework versions. You can get source code and try to recompile it yourself
