### ISSUE TITLE
Should support GLOBAL_QUOTE function

### ISSUE THREAD

**Issue by dp-github** [LutsenkoKirill/AlphaVantage.Net#11]
Love the library  - thanks for making it!

I found that I needed to edit ApiFunctions.cs to add the `GLOBAL_QUOTE` function.  This is an important function, because many securities are unavailable in `BATCH_QUOTES` which can be priced using `GLOBAL_QUOTE`.

Note that, when using `GLOBAL_QUOTE`, the parameter is named "symbol" instead of "symbols" as used in `BATCH_QUOTES`.

**Comment by LutsenkoKirill** [comment]
@dp-github hi, thank you for the note. Yep, it will be supported in the next version that I'm preparing now

**Comment by LutsenkoKirill** [comment]
Fixed in v2. Preview is already available: https://github.com/LutsenkoKirill/AlphaVantage.Net/tree/v2
