### ISSUE TITLE
Concurrent requests counter not reset

### ISSUE THREAD

**Issue by noakesey** [LutsenkoKirill/AlphaVantage.Net#12]
Hi,

I'm not sure this logic is correct - it doesn't seem as though the semaphore is released.  After 10  (default) requests it stalls on WaitOne().  I think the catch should be a finally (without throw)?

        public async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request)
        {
            HttpResponseMessage response = null;
            _concurrentRequestsCounter.WaitOne();
            await WaitForRequestedMinimumInterval();
            try
            {
                response = await _client.SendAsync(request);
            }
            catch
            {
                _concurrentRequestsCounter.Release();
                throw;
            }
            return response;
        }

At least that change solved my issue!

**Comment by timurig** [comment]
Yea, the hard-coded 10 request per minute is kind of confusing. In my case I've realized that after sending complain to AlphaAdvantage :)

**Comment by LutsenkoKirill** [comment]
Fixed in v2. Preview is already available: https://github.com/LutsenkoKirill/AlphaVantage.Net/tree/v2
