### ISSUE TITLE
HttpClientWithRateLimit: constructor is internal

### ISSUE THREAD

**Issue by f00f** [LutsenkoKirill/AlphaVantage.Net#19]
It's awesome that you provide a rate-limited HttpClient. However, I cannot figure out how to use it as its constructor is internal. Is there an example somewhere?

**Comment by LutsenkoKirill** [comment]
@f00f will be fixed in v 2.0.2. 
Thanks for @JackSteel97

**Comment by f00f** [comment]
FTR: fixed in https://github.com/LutsenkoKirill/AlphaVantage.Net/pull/20
