### ISSUE TITLE
Question about tests

### ISSUE THREAD

**Issue by rasodu** [LutsenkoKirill/AlphaVantage.Net#4]
Are tests making actual calls to API?
Some of the tests fail when I run all of them together.
But failed tests run fine when I run them individually. So I am thinking those tests are failing because of API call failure.

**Comment by LutsenkoKirill** [comment]
@rasodu yes, they actually call API. I tried to find delay which makes them work fine but if you have problem on your machine it looks like it worked only for me

**Comment by rasodu** [comment]
I run the tests a few times. Seems like they are working fine. I think since we are limiting the number of API calls to 20 a minutes, we don't see API call failure anymore.
