### ISSUE TITLE
Can we please provide our own HttpClient?

### ISSUE THREAD

**Issue by VictorioBerra** [LutsenkoKirill/AlphaVantage.Net#8]
I need to be able to use [outgoing middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2) and [Polly ](https://github.com/App-vNext/Polly). I need more control over the HttpClient

**Comment by rasodu** [comment]
@VictorioBerra  Are you still interested in the enhancement?

**Comment by VictorioBerra** [comment]
As of right now I do not have a pressing need for it but I can see it being very useful for others and possibly myself in the future.

**Comment by clausjensen** [comment]
@rasodu Just did a quick and dirty fix for this - mostly to see if it would work as I haven't really used proxies much. You're welcome to use the code as inspiration if you want to implement this (but please make it prettier if you do 😃) ... I think it would solve the problem of having more control over HttpClient.

https://github.com/clausjensen/AlphaVantage.Net/commit/c54352474242f19be02d22fcdded63cd7a07fd43

(started from this stackoverflow question: https://stackoverflow.com/questions/59562444/c-sharp-alphavantage-net-how-to-use-proxy)

**Comment by LutsenkoKirill** [comment]
@VictorioBerra  in the next version that I'm preparing now I'll provide more grain control over the HttpClient

**Comment by LutsenkoKirill** [comment]
Fixed in v2. Preview is already available: https://github.com/LutsenkoKirill/AlphaVantage.Net/tree/v2

**Comment by VictorioBerra** [comment]
Thank you!
